-- -----------------------------------------------------
-- Insercion de Datos
-- -----------------------------------------------------

USE LabRem_Digital;

-- -----------------------------------------------------
-- Laboratorios
-- -----------------------------------------------------

INSERT INTO Laboratorios (area, nombre, descripcion) 
VALUES 
(DEFAULT,'Transmisor/Receptor UART','<p>Tiene como objetivo validar el diseño e implementación de un Transmisor/Receptor UART en un dispositivo FPGA. Se espera que el estudiante genere competencias en evaluar, diagnosticar y corregir el diseño lógico de una interfaz UART en FPGA para el normal funcionamiento. <br/>La comunicación se evalúa entre dos terminales: 1)-dispositivo FPGA que contiene la interfaz uart y 2)-una PC que contiene una interfaz gráfica que monitorea la comunicación. El dispositivo FPGA se conecta a la PC mediante un adaptador usb/uart el cual permite emular una comunicación en la PC mediante su puerto usb. La PC ejecuta una aplicación de código libre que permite transferir datos hacia y desde el dispositivo FPGA respectivamente. Como parámetro de entrada en la prueba de transmisión y recepción, el estudiante debe especificar velocidad, cantidad de bits del dato, tipo de paridad, cantidad de bits de parada, cadena de caracteres a transmitir desde FPGA a PC y dato a transmitir desde PC a FPGA. Finalmente los configura en el dispositivo en ambos terminales. <br/>En la prueba de transmisión el estudiante debe: <br/>1)-Definir el mensaje que desea transmitir desde el dispositivo FPGA como una cadena de caracteres ascii. <br/>2)-Enviar los datos desde la interfaz hacia la PC vía adaptador usb/uart <br/>3)-Chequear en la aplicación que monitorea el puerto serie que se recibe adecuadamente la cadena de caracteres. <br/>En la prueba de recepción el estudiante debe: <br/>1)-Define el dato que desea enviar desde el monitor del puerto serie en la pc hacia la interfaz implementada en el dispositivo FPGA. <br/>2)-Enviar el dato desde la PC. <br/>3)-El dispositivo FPGA recibe el dato y lo visualiza en 8 leds disponibles en el sistema de desarrollo que aloja el dispositivo FPGA. Finalmente el estudiante debe identificar el error en el diseño lógico en caso de no ser correcta la cadena recibida o enviada por el dispositivo FPGA, lo corrige, reprograma y vuelve a repetir el procedimiento. Como resultado se desea visualizar tensiones (o estados lógicos) de bits de transmisión y recepción en función del tiempo. <br/>Para desarrollar esta experiencia actualmente se dispone de dos placas educacionales FPGA Cyclone II y tres placas educacionales FPGA Cyclone IV. Además se cuenta con conversores USB/UART.</p>'),
(DEFAULT,'Transmisor/Receptor I2C','<p>La experiencia tiene como objetivo validar el diseño e implementación de una comunicación serie sincrónica maestro-esclavo I2C en un dispositivo FPGA. Se espera que el estudiante adquiera competencias en evaluar, diagnosticar y corregir el diseño de una interfaz I2C en FPGA para el normal funcionamiento. <br/>La comunicación I2C se evalúa entre dos terminales: 1) dispositivo FPGA que hace las veces de maestro y 2) una memoria EEPROM que hace las veces de esclavo. <br/>El dispositivo FPGA se conecta a la memoria mediante una interfaz I2C. Desde el dispositivo FPGA se solicita leer o escribir la memoria EEPROM. La lectura de un byte en la memoria se implementa visualizando en 8 leds la palabra binaria. La escritura se realiza enviando a la memoria la dirección de escritura y el dato a escribir. <br/>Los datos y/o parámetros de entrada necesarios para la experiencia son frecuencia de la comunicación, dirección de la memoria para leer o escribir, dato a escribir en la memoria en caso de una escritura, señal que habilita la lectura o la escritura. <br/>Se espera medir las Tensiones (o estados lógicos) de bits de transmisión y recepción en función del tiempo. <br/>Para visualización de resultados en el caso de leer la memoria se implementa mediante un conjunto de 8 leds, en caso de escritura se implementa escribiendo un dato en la memoria y luego, mediante un proceso de lectura chequeando ese dato en 8 leds en la placa de prueba. Para esta experiencia se cuenta con el mismo equipamiento descrito en la experiencia del apartado a) de este LR.</p>');

-- -----------------------------------------------------
-- Ensayos
-- -----------------------------------------------------

-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);


-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);