version: '3.8'
services:
  db:
    container_name: labrem-apps-db-teleco-dev
    image: mysql:8.0.30
    environment:
      TZ: America/Buenos_Aires
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/a.sql:ro
      - ./database/db-triggers.sql:/docker-entrypoint-initdb.d/b.sql:ro
      - ./database/db-sp-laboratorios.sql:/docker-entrypoint-initdb.d/c.sql:ro
      - ./database/db-sp-ensayos.sql:/docker-entrypoint-initdb.d/d.sql:ro
      - teleco-db:/var/lib/mysql
    networks:
      labrem-network:
        aliases:
          - labrem-apps-db-teleco-dev
  server:
    depends_on:
      - db
    container_name: labrem-apps-server-teleco-dev
    build:
      context: ./server
      no_cache: true
      dockerfile_inline: |
        FROM node:18.17.0
        WORKDIR /usr/src/server
        RUN npm install -g nodemon
        EXPOSE 3000
        CMD ["npm","run","dev"]
    environment:
      NODE_ENV:   development
      DB_HOST:    labrem-apps-db-teleco-dev
      DB_DIALECT: mysql
      DB_USER:    ${MYSQL_USER}
      DB_PASS:    ${MYSQL_PASSWORD}
      DB_NAME:    ${MYSQL_DATABASE}
      DB_PORT:    3306
    ports:
      - ${SERVER_PORT}:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /home/francoq/labrem/teleco/server:/usr/src/server
    networks:
      labrem-network:
        aliases:
          - labrem-apps-server-teleco-dev
networks:
  labrem-network:
    external: true
volumes:
  teleco-db:
    name: teleco-db
