version: '3.8'
services:
  db:
    container_name: fisica-db
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - TZ=America/Buenos_Aires
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ../volumenes/fisica-db:/var/lib/mysql
    networks:
      labrem:
        aliases:
          - fisica-db
  server:
    depends_on:
      - db
    container_name: fisica-server
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_DIALECT=$DB_DIALECT
      - SERVER_PORT=$SERVER_DOCKER_PORT
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      labrem:
        aliases:
          - fisica-server
networks:
  labrem:
    name: labrem-net
    driver: bridge
    ipam:
      driver: default
